-- Supabase CMS schema for portfolio landing page
-- Jalankan di Supabase Dashboard > SQL Editor > New Query

-- 1. PROFILE (single row, id = 1)
-- 1. PROFILE (single row, id = 1)
create table if not exists public.profile (
  id bigint generated by default as identity primary key, -- Ditolong pakai 'by default'
  full_name text not null default 'Fahril Sidik Alfarizi',
  tagline text not null default 'AI/ML Engineer | AI Automation | Data Scientist | Frontend Developer',
  bio text not null default '',
  photo_url text default '',
  resume_url text default '',
  credential_url text default '',
  socials jsonb not null default '{"linkedin":"","instagram":"","github":""}'::jsonb,
  email text default '',
  location text default '',
  updated_at timestamptz not null default now()
);

-- 2. EDUCATION
create table if not exists public.education (
  id bigint generated by default as identity primary key,
  school text not null default '',
  major text not null default '',
  start_year text not null default '',
  end_year text not null default '',
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

-- 3. EXPERIENCES
create table if not exists public.experiences (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('works','professional')),
  title text not null default '',
  company text not null default '',
  date_text text not null default '',
  bullets text[] not null default '{}',
  link_url text default '',
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

-- 4. SKILLS
create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  logo_url text default '',
  level int not null default 70 check (level >= 0 and level <= 100),
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

-- 5. PROJECTS
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  technologies text[] not null default '{}',
  category text not null default 'ML' check (category in ('ML','Web','CV','NLP','n8n')),
  year_text text default '',
  web_url text default '',
  repo_url text default '',
  sort_order int not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now()
);

-- 6. SITE SETTINGS (single row, id = 1)
create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  formspree_id text default '',
  footer_text text default '© 2025 | Fahril Sidik Alfarizi',
  created_at timestamptz not null default now()
);

-- Seed single-row tables jika kosong
insert into public.profile (id, full_name, tagline, bio, credential_url, socials, email, location)
values (
  1,
  'Fahril Sidik Alfarizi',
  'AI/ML Engineer | AI Automation | Data Scientist | Frontend Developer',
  'I am a AI Engineer with a focus on Machine Learning and Deep Learning. I am a Computer Science/Information Engineering graduate from the Garut Institute of Technology and a graduate of Bangkit Academy 2024 Batch 1 (Machine Learning path). I have experience building deep learning models using TensorFlow, from data processing to implementation, and am interested in creating innovative data-driven solutions.',
  'https://www.notion.so/Licence-Credential-Fahril-Sidik-Alfarizi-6db2fb315d884612aef994a956ece0c5?source=copy_link',
  '{"linkedin":"https://www.linkedin.com/in/fahril-sidik-alfarizi/","instagram":"https://www.instagram.com/fhrlalfrz_?igsh=bGMxcG1yNWxjdjdu","github":"https://github.com/fahrilalfariziii"}',
  'fahrilsidik207@gmail.com',
  'West Java, Indonesia'
)
on conflict (id) do nothing;

insert into public.site_settings (id, formspree_id, footer_text)
values (1, 'xeopjjeg', '© 2025 | Fahril Sidik Alfarizi')
on conflict (id) do nothing;

-- Enable RLS: baca publik, tulis hanya admin (authenticated)
alter table public.profile enable row level security;
alter table public.education enable row level security;
alter table public.experiences enable row level security;
alter table public.skills enable row level security;
alter table public.projects enable row level security;
alter table public.site_settings enable row level security;

-- Hapus policy lama bila re-run
drop policy if exists "public read" on public.profile;
drop policy if exists "admin write" on public.profile;
drop policy if exists "public read" on public.education;
drop policy if exists "admin write" on public.education;
drop policy if exists "public read" on public.experiences;
drop policy if exists "admin write" on public.experiences;
drop policy if exists "public read" on public.skills;
drop policy if exists "admin write" on public.skills;
drop policy if exists "public read" on public.projects;
drop policy if exists "admin write" on public.projects;
drop policy if exists "public read" on public.site_settings;
drop policy if exists "admin write" on public.site_settings;

create policy "public read" on public.profile for select using (true);
create policy "admin write" on public.profile for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "public read" on public.education for select using (true);
create policy "admin write" on public.education for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "public read" on public.experiences for select using (true);
create policy "admin write" on public.experiences for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "public read" on public.skills for select using (true);
create policy "admin write" on public.skills for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "public read" on public.projects for select using (true);
create policy "admin write" on public.projects for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "public read" on public.site_settings for select using (true);
create policy "admin write" on public.site_settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Storage buckets (buat via Dashboard > Storage jika belum ada):
--   profile-photos (public), skill-logos (public), resumes (public)
-- Policy storage yang disarankan:
--   SELECT public, INSERT/UPDATE/DELETE authenticated.
-- Bisa diatur dari Dashboard > Storage > Policies.
