-- Supabase CMS schema for portfolio landing page
-- Jalankan di Supabase Dashboard > SQL Editor > New Query

-- 1. PROFILE (single row, id = 1) — photo/resume via proxy hide supabase.co
create table if not exists public.profile (
  id bigint generated by default as identity primary key,
  full_name text not null default 'Fahril Sidik Alfarizi' check (char_length(full_name) <= 80),
  tagline text not null default 'AI/ML Engineer | AI Automation | Data Scientist | Frontend Developer' check (char_length(tagline) <= 120),
  bio text not null default '' check (char_length(bio) <= 1000),
  photo_url text default '' check (photo_url = '' or photo_url ~ '^https?://' or photo_url ~ '^/api/file'),
  resume_url text default '' check (resume_url = '' or resume_url ~ '^https?://' or resume_url ~ '^resume/' or resume_url ~ '^/api/resume'),
  credential_url text default '' check (credential_url = '' or credential_url ~ '^https?://'),
  socials jsonb not null default '{"linkedin":"","instagram":"","github":""}'::jsonb,
  email text default '' check (email = '' or email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  location text default '' check (char_length(location) <= 80),
  updated_at timestamptz not null default now()
);

-- 2. EDUCATION
create table if not exists public.education (
  id bigint generated by default as identity primary key,
  school text not null default '' check (char_length(school) <= 120),
  major text not null default '' check (char_length(major) <= 120),
  start_year text not null default '' check (char_length(start_year) <= 10),
  end_year text not null default '' check (char_length(end_year) <= 10),
  sort_order int not null default 0 check (sort_order >= 0 and sort_order <= 1000),
  created_at timestamptz not null default now()
);

-- 3. EXPERIENCES
create table if not exists public.experiences (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('works','professional')),
  title text not null default '' check (char_length(title) <= 80),
  company text not null default '' check (char_length(company) <= 80),
  date_text text not null default '' check (char_length(date_text) <= 40),
  bullets text[] not null default '{}' check (array_length(bullets,1) is null or array_length(bullets,1) <= 20),
  link_url text default '' check (link_url = '' or link_url ~ '^https?://'),
  sort_order int not null default 0 check (sort_order >= 0 and sort_order <= 1000),
  created_at timestamptz not null default now()
);

-- 4. SKILLS — logo via proxy hide supabase.co
create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) >= 1 and char_length(name) <= 40),
  logo_url text default '' check (logo_url = '' or logo_url ~ '^https?://' or logo_url ~ '^/api/file' or logo_url ~ '^assets/'),
  level int not null default 70 check (level >= 0 and level <= 100),
  sort_order int not null default 0 check (sort_order >= 0 and sort_order <= 1000),
  created_at timestamptz not null default now()
);

-- 5. PROJECTS
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) >= 2 and char_length(title) <= 80),
  description text not null default '' check (char_length(description) <= 500),
  technologies text[] not null default '{}' check (array_length(technologies,1) is null or array_length(technologies,1) <= 12),
  category text not null default 'ML' check (category in ('ML','Web','CV','NLP','n8n')),
  year_text text default '' check (char_length(year_text) <= 60),
  web_url text default '' check (web_url = '' or web_url ~ '^https?://'),
  repo_url text default '' check (repo_url = '' or repo_url ~ '^https?://'),
  sort_order int not null default 0 check (sort_order >= 0 and sort_order <= 1000),
  is_visible boolean not null default true,
  created_at timestamptz not null default now()
);

-- 6. SITE SETTINGS (single row, id = 1)
create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  formspree_id text default '' check (formspree_id = '' or formspree_id ~ '^[a-zA-Z0-9_-]{6,20}$'),
  footer_text text default '© 2025 | Fahril Sidik Alfarizi' check (char_length(footer_text) <= 120),
  created_at timestamptz not null default now()
);

-- Migration: izinkan proxy path tanpa supabase.co untuk DB yang sudah ada
do $$ begin
  alter table public.profile drop constraint if exists profile_photo_url_check;
  alter table public.profile add constraint profile_photo_url_check check (photo_url = '' or photo_url ~ '^https?://' or photo_url ~ '^/api/file');
exception when others then null; end $$;
do $$ begin
  alter table public.profile drop constraint if exists profile_resume_url_check;
  alter table public.profile add constraint profile_resume_url_check check (resume_url = '' or resume_url ~ '^https?://' or resume_url ~ '^resume/' or resume_url ~ '^/api/resume');
exception when others then null; end $$;
do $$ begin
  alter table public.skills drop constraint if exists skills_logo_url_check;
  alter table public.skills add constraint skills_logo_url_check check (logo_url = '' or logo_url ~ '^https?://' or logo_url ~ '^/api/file' or logo_url ~ '^assets/');
exception when others then null; end $$;

-- Seed single-row tables jika kosong
insert into public.profile (id, full_name, tagline, bio, credential_url, socials, email, location)
values (
  1,
  'Fahril Sidik Alfarizi',
  'AI/ML Engineer | AI Automation | Data Scientist | Frontend Developer',
  'I am a AI Engineer with a focus on Machine Learning and Deep Learning. I am a Computer Science/Information Engineering graduate from the Garut Institute of Technology and a graduate of Bangkit Academy 2024 Batch 1 (Machine Learning path). I have experience building deep learning models using TensorFlow, from data processing to implementation, and am interested in creating innovative data-driven solutions.',
  'https://www.notion.so/Licence-Credential-Fahril-Sidik-Alfarizi-6db2fb315d884612aef994a956ece0c5?source=copy_link',
  '{"linkedin":"https://www.linkedin.com/in/fahril-sidik-alfarizi/","instagram":"https://www.instagram.com/fhrlalfrz_?igsh=bGMxcG1yNWxjdjdu","github":"https://github.com/fahrilalfariziii"}',
  'fahrilsidik207@gmail.com',
  'West Java, Indonesia'
)
on conflict (id) do nothing;

insert into public.site_settings (id, formspree_id, footer_text)
values (1, 'xeopjjeg', '© 2025 | Fahril Sidik Alfarizi')
on conflict (id) do nothing;

-- Enable RLS: baca publik, tulis hanya admin via service_role (bypass RLS) lewat /api/admin
-- Frontend tidak lagi pakai anon key langsung, jadi policy "authenticated" tidak diperlukan.
-- Kita tetap biarkan public read, tapi tulis hanya service_role (atau admin email tertentu).
alter table public.profile enable row level security;
alter table public.education enable row level security;
alter table public.experiences enable row level security;
alter table public.skills enable row level security;
alter table public.projects enable row level security;
alter table public.site_settings enable row level security;

-- Hapus policy lama bila re-run
drop policy if exists "public read" on public.profile;
drop policy if exists "admin write" on public.profile;
drop policy if exists "allow service_role write" on public.profile;
drop policy if exists "public read" on public.education;
drop policy if exists "admin write" on public.education;
drop policy if exists "allow service_role write" on public.education;
drop policy if exists "public read" on public.experiences;
drop policy if exists "admin write" on public.experiences;
drop policy if exists "allow service_role write" on public.experiences;
drop policy if exists "public read" on public.skills;
drop policy if exists "admin write" on public.skills;
drop policy if exists "allow service_role write" on public.skills;
drop policy if exists "public read" on public.projects;
drop policy if exists "admin write" on public.projects;
drop policy if exists "allow service_role write" on public.projects;
drop policy if exists "public read" on public.site_settings;
drop policy if exists "admin write" on public.site_settings;
drop policy if exists "allow service_role write" on public.site_settings;

-- Public read untuk semua (portfolio publik)
create policy "public read" on public.profile for select using (true);
create policy "public read" on public.education for select using (true);
create policy "public read" on public.experiences for select using (true);
create policy "public read" on public.skills for select using (true);
create policy "public read" on public.projects for select using (true);
create policy "public read" on public.site_settings for select using (true);

-- Write hanya via service_role (digunakan oleh /api/* server). 
-- Authenticated anon TIDAK bisa tulis lagi — cegah anon key abuse.
-- Jika kamu masih butuh direct anon write untuk dev lokal, ganti ke:
--   using (auth.email() = 'admin@kamu.com') tapi service_role lebih aman.
create policy "allow service_role write" on public.profile for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "allow service_role write" on public.education for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "allow service_role write" on public.experiences for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "allow service_role write" on public.skills for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "allow service_role write" on public.projects for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "allow service_role write" on public.site_settings for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- Storage buckets (buat via Dashboard > Storage jika belum ada):
--   profile-photos (public), skill-logos (public), resumes (public)
-- Storage RLS harus diatur terpisah di storage.objects:
-- Contoh policy (jalankan sekali):
--   create policy "public read storage" on storage.objects for select using (bucket_id in ('profile-photos','skill-logos','resumes'));
--   create policy "service_role write storage" on storage.objects for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
-- Jangan buat policy INSERT untuk authenticated anon lagi.
